apiVersion: v1
kind: Service
metadata:
  name: {{ include "llama-stack.fullname" . }}
  labels:
    {{- include "llama-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "llama-stack.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}   # 8321
      targetPort: http
